// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.3
// source: proto/pruebas.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Pruebasgrpc_Saludar_FullMethodName = "/proto.pruebasgrpc/Saludar"
)

// PruebasgrpcClient is the client API for Pruebasgrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PruebasgrpcClient interface {
	Saludar(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type pruebasgrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPruebasgrpcClient(cc grpc.ClientConnInterface) PruebasgrpcClient {
	return &pruebasgrpcClient{cc}
}

func (c *pruebasgrpcClient) Saludar(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Pruebasgrpc_Saludar_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PruebasgrpcServer is the server API for Pruebasgrpc service.
// All implementations must embed UnimplementedPruebasgrpcServer
// for forward compatibility
type PruebasgrpcServer interface {
	Saludar(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPruebasgrpcServer()
}

// UnimplementedPruebasgrpcServer must be embedded to have forward compatible implementations.
type UnimplementedPruebasgrpcServer struct {
}

func (UnimplementedPruebasgrpcServer) Saludar(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Saludar not implemented")
}
func (UnimplementedPruebasgrpcServer) mustEmbedUnimplementedPruebasgrpcServer() {}

// UnsafePruebasgrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PruebasgrpcServer will
// result in compilation errors.
type UnsafePruebasgrpcServer interface {
	mustEmbedUnimplementedPruebasgrpcServer()
}

func RegisterPruebasgrpcServer(s grpc.ServiceRegistrar, srv PruebasgrpcServer) {
	s.RegisterService(&Pruebasgrpc_ServiceDesc, srv)
}

func _Pruebasgrpc_Saludar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruebasgrpcServer).Saludar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pruebasgrpc_Saludar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruebasgrpcServer).Saludar(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Pruebasgrpc_ServiceDesc is the grpc.ServiceDesc for Pruebasgrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pruebasgrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.pruebasgrpc",
	HandlerType: (*PruebasgrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Saludar",
			Handler:    _Pruebasgrpc_Saludar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pruebas.proto",
}
